export const AUDIT_ACTIONS = {
  ADMIN_ACCESS: "ADMIN_ACCESS",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  PRODUCT_BULK: "PRODUCT_BULK",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CATEGORY_DELETED: "CATEGORY_DELETED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  CUSTOMER_DISABLED: "CUSTOMER_DISABLED",
  CUSTOMER_ENABLED: "CUSTOMER_ENABLED",
  ORDER_UPDATED: "ORDER_UPDATED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  IMAGE_UPLOADED: "IMAGE_UPLOADED",
  IMAGE_DELETED: "IMAGE_DELETED",
  SUPPORT_ACTION: "SUPPORT_ACTION",
};

export default AUDIT_ACTIONS;
