export const NOTIFICATION_TYPES = {
  LOW_STOCK: "LOW_STOCK",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  NEW_ORDER: "NEW_ORDER",
  CANCELLED_ORDER: "CANCELLED_ORDER",
  NEW_CUSTOMER: "NEW_CUSTOMER",
  FAILED_PAYMENT: "FAILED_PAYMENT",
  SUPPORT_REQUEST: "SUPPORT_REQUEST",
};

export default NOTIFICATION_TYPES;
